(define (problem ThreePeg-TwoDisk)
    (:domain hanoi)
  (:objects p1 p2 p3 d1 d2)
  (:goal (and (onpeg d2 p3) (ontable d2) (on d1 d2)))
  (:init (onpeg d1 p1)
  		 (onpeg d2 p1)
  		 (on d1 d2)
  		 (ontable d2)
		 (clear d1)
		 (handempty)
  		 (isdisk d1)
  		 (isdisk d2)
  		 (issmaller d1 d2)
  		 (ispeg p1)
  		 (ispeg p2)
  		 (ispeg p3)
  		 (pegclear p2)
  		 (pegclear p3)))